/**
  * @file      coffee2_io_names.h
  * @brief     Define Coffee2 target-owned human-readable IO names.
  */

#ifndef COFFEE2_IO_NAMES_H
#define COFFEE2_IO_NAMES_H

#define COFFEE2_IO_NAME_LOCAL_DI_1   "DI1_OUTLET_DOOR_UPPER_LIMIT"
#define COFFEE2_IO_NAME_LOCAL_DI_2   "DI2_OUTLET_DOOR_LOWER_LIMIT"
#define COFFEE2_IO_NAME_LOCAL_DI_3   "DI3_COFFEE_WATER_TANK_HIGH_LEVEL"
#define COFFEE2_IO_NAME_LOCAL_DI_4   "DI4_COFFEE_WATER_TANK_LOW_LEVEL"
#define COFFEE2_IO_NAME_LOCAL_DI_5   "DI5_HOT_WATER_TANK_HIGH_LEVEL"
#define COFFEE2_IO_NAME_LOCAL_DI_6   "DI6_HOT_WATER_TANK_LOW_LEVEL"
#define COFFEE2_IO_NAME_LOCAL_DI_7   "DI7_RESERVED"
#define COFFEE2_IO_NAME_LOCAL_DI_8   "DI8_RESERVED"

#define COFFEE2_IO_NAME_LOCAL_DO_1   "DO1_OUTLET_DOOR_UP"
#define COFFEE2_IO_NAME_LOCAL_DO_2   "DO2_OUTLET_DOOR_DOWN"
#define COFFEE2_IO_NAME_LOCAL_DO_3   "DO3_HOT_WATER_SUPPLY_PUMP"
#define COFFEE2_IO_NAME_LOCAL_DO_4   "DO4_COFFEE_WATER_TANK_SUPPLY_PUMP"
#define COFFEE2_IO_NAME_LOCAL_DO_5   "DO5_RESERVED"
#define COFFEE2_IO_NAME_LOCAL_DO_6   "DO6_RESERVED"
#define COFFEE2_IO_NAME_LOCAL_DO_7   "DO7_RESERVED"
#define COFFEE2_IO_NAME_LOCAL_DO_8   "DO8_RESERVED"

#define COFFEE2_IO_NAME_MB1_DI_1    "X01_FINISHED_FRONT_CUP"
#define COFFEE2_IO_NAME_MB1_DI_2    "X02_FINISHED_REAR_CUP"
#define COFFEE2_IO_NAME_MB1_DI_3    "X03_OUTLET_CUP"
#define COFFEE2_IO_NAME_MB1_DI_4    "X04_PURE_WATER_BUCKET1_LOW_LEVEL"
#define COFFEE2_IO_NAME_MB1_DI_5    "X05_WASTE_RESIDUE_BIN"
#define COFFEE2_IO_NAME_MB1_DI_6    "X06_WASTE_LIQUID_BUCKET"
#define COFFEE2_IO_NAME_MB1_DI_7    "X07_WASTE_LIQUID_HIGH_LEVEL"
#define COFFEE2_IO_NAME_MB1_DI_8    "X08_RESERVED"
#define COFFEE2_IO_NAME_MB1_DI_9    "X09_RESERVED"
#define COFFEE2_IO_NAME_MB1_DI_10   "X10_RESERVED"
#define COFFEE2_IO_NAME_MB1_DI_11   "X11_MILK_BOX_R1_LEVEL"
#define COFFEE2_IO_NAME_MB1_DI_12   "X12_FRUIT_DRINK_A_R2_LEVEL"
#define COFFEE2_IO_NAME_MB1_DI_13   "X13_FRUIT_DRINK_B_R3_LEVEL"
#define COFFEE2_IO_NAME_MB1_DI_14   "X14_RESERVED"
#define COFFEE2_IO_NAME_MB1_DI_15   "X15_RESERVED"
#define COFFEE2_IO_NAME_MB1_DI_16   "X16_RESERVED"

#define COFFEE2_IO_NAME_MB2_DO_1    "Y11_WATER_HEATER_RELAY"
#define COFFEE2_IO_NAME_MB2_DO_2    "Y12_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_3    "Y13_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_4    "Y14_MILK_BOX_R1_SOLENOID_VALVE"
#define COFFEE2_IO_NAME_MB2_DO_5    "Y15_FRUIT_DRINK_A_R2_SOLENOID_VALVE"
#define COFFEE2_IO_NAME_MB2_DO_6    "Y16_FRUIT_DRINK_B_R3_SOLENOID_VALVE"
#define COFFEE2_IO_NAME_MB2_DO_7    "Y17_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_8    "Y18_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_9    "Y19_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_10   "Y20_FRUIT_DRINK_A_PERISTALTIC_PUMP"
#define COFFEE2_IO_NAME_MB2_DO_11   "Y21_FRUIT_DRINK_B_PERISTALTIC_PUMP"
#define COFFEE2_IO_NAME_MB2_DO_12   "Y22_ASSIST_PERISTALTIC_PUMP"
#define COFFEE2_IO_NAME_MB2_DO_13   "Y23_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_14   "Y24_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_15   "Y25_RESERVED"
#define COFFEE2_IO_NAME_MB2_DO_16   "Y26_RESERVED"

#endif
