/**
  * @file      device_library.h
  * @brief     Define product-independent device library identities.
  * @author    WHong
  * @date      2026-08-20
  */

#ifndef DEVICE_LIBRARY_H
#define DEVICE_LIBRARY_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

typedef enum {
	DEVICE_CATEGORY_NONE = 0,
	DEVICE_CATEGORY_ROBOT = 1,
	DEVICE_CATEGORY_COFFEE_MACHINE = 2,
	DEVICE_CATEGORY_CUP_MACHINE = 3,
	DEVICE_CATEGORY_SYRUP_MACHINE = 4,
	DEVICE_CATEGORY_LID_MACHINE = 5,
	DEVICE_CATEGORY_ICE_MACHINE = 6,
	DEVICE_CATEGORY_SCALE = 7,
	DEVICE_CATEGORY_POWER_METER = 8,
	DEVICE_CATEGORY_IO = 9
} DeviceCategory_e;

typedef enum {
	DEVICE_ROLE_NONE = 0,
	DEVICE_ROLE_ROBOT_1 = 1,
	DEVICE_ROLE_ROBOT_2 = 2,
	DEVICE_ROLE_ROBOT_3 = 3,
	DEVICE_ROLE_COFFEE_MACHINE = 10,
	DEVICE_ROLE_CUP_MACHINE = 11,
	DEVICE_ROLE_SYRUP_MACHINE = 12,
	DEVICE_ROLE_LID_MACHINE = 13,
	DEVICE_ROLE_ICE_MACHINE = 14,
	DEVICE_ROLE_SCALE = 15,
	DEVICE_ROLE_POWER_METER = 16,
	DEVICE_ROLE_IO_INPUT = 17,
	DEVICE_ROLE_IO_OUTPUT = 18
} DeviceRole_e;

typedef enum {
	DEVICE_PROTOCOL_NONE = 0,
	DEVICE_PROTOCOL_MODBUS_RTU = 1,
	DEVICE_PROTOCOL_MODBUS_TCP = 2,
	DEVICE_PROTOCOL_COFFEE_F200_UART = 3,
	DEVICE_PROTOCOL_JAKA_RESERVED = 4,
	DEVICE_PROTOCOL_LOCAL_GPIO = 5
} DeviceProtocolId_e;

typedef enum {
	DEVICE_DRIVER_NONE = 0,
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_1 = 1,
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_2 = 2,
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_3 = 3,
	DEVICE_DRIVER_ROBOT_JAKA_RESERVED = 4,
	DEVICE_DRIVER_COFFEE_KALERM_O_MODBUS = 10,
	DEVICE_DRIVER_COFFEE_KALERM_X_MODBUS = 11,
	DEVICE_DRIVER_COFFEE_DRCOFFEE_F200 = 12,
	DEVICE_DRIVER_COFFEE_M50_MODBUS = 13,
	DEVICE_DRIVER_CUP_SHENGSHU_MODBUS = 20,
	DEVICE_DRIVER_SYRUP_CURRENT_MODBUS = 21,
	DEVICE_DRIVER_LID_SHENGSHU_MODBUS = 22,
	DEVICE_DRIVER_ICE_CURRENT_MODBUS = 23,
	DEVICE_DRIVER_SCALE_BSQ_DG_V2 = 24,
	DEVICE_DRIVER_POWER_METER_DDSU666 = 25,
	DEVICE_DRIVER_IO_MODBUS_DIGITAL = 26
} DeviceDriverId_e;

#define DEVICE_DRIVER_ROBOT_DOBOT_LEGACY_3139 \
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_1
#define DEVICE_DRIVER_ROBOT_DOBOT_EXTENDED_3150 \
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_2
#define DEVICE_DRIVER_CUP_MODBUS \
	DEVICE_DRIVER_CUP_SHENGSHU_MODBUS
#define DEVICE_DRIVER_SYRUP_MODBUS \
	DEVICE_DRIVER_SYRUP_CURRENT_MODBUS
#define DEVICE_DRIVER_LID_MODBUS \
	DEVICE_DRIVER_LID_SHENGSHU_MODBUS
#define DEVICE_DRIVER_ICE_MODBUS \
	DEVICE_DRIVER_ICE_CURRENT_MODBUS
#define DEVICE_DRIVER_SCALE_MODBUS \
	DEVICE_DRIVER_SCALE_BSQ_DG_V2
#define DEVICE_DRIVER_POWER_METER_MODBUS \
	DEVICE_DRIVER_POWER_METER_DDSU666
#define DEVICE_DRIVER_IO_MODBUS \
	DEVICE_DRIVER_IO_MODBUS_DIGITAL

typedef enum {
	DEVICE_TRANSPORT_NONE = 0,
	DEVICE_TRANSPORT_UART = 1,
	DEVICE_TRANSPORT_TCP = 2,
	DEVICE_TRANSPORT_LOCAL_GPIO = 3
} DeviceTransportType_e;

typedef struct {
	DeviceDriverId_e xDriverId;
	DeviceCategory_e xCategory;
	DeviceProtocolId_e xRequiredProtocol;
} DeviceDriverDescriptor_t;

/** @brief Let a public device action observe product cancellation. */
typedef uint8_t (*DeviceCancelCheck_t)(const void *pvContext);

#ifdef __cplusplus
}
#endif

#endif /* DEVICE_LIBRARY_H */
