/**
  * @file coffee3_device_bindings.h
  * @brief Coffee3-only immutable device selection, routing and diagnostic names.
  * @date 2026-09-07
  * @note Included only by coffee3_device.c; no runtime registration.
  */
#ifndef COFFEE3_DEVICE_BINDINGS_H
#define COFFEE3_DEVICE_BINDINGS_H

#if (COFFEE3_ROBOT_PROTOCOL_VARIANT == \
	COFFEE3_ROBOT_PROTOCOL_2)
#define COFFEE3_ROBOT_DRIVER_ID \
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_2
#elif (COFFEE3_ROBOT_PROTOCOL_VARIANT == \
	COFFEE3_ROBOT_PROTOCOL_3)
#define COFFEE3_ROBOT_DRIVER_ID \
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_3
#else
#define COFFEE3_ROBOT_DRIVER_ID \
	DEVICE_DRIVER_ROBOT_DOBOT_PROTOCOL_1
#endif

/** @brief Immutable product device-to-bus binding table. */
static const Coffee3DeviceBinding_t s_axBindings[] = {
	{ COFFEE3_DEVICE_ROBOT, 0U, COFFEE3_ROBOT_UNIT_ID, 0U,
		DEVICE_CATEGORY_ROBOT, DEVICE_ROLE_ROBOT_1,
		COFFEE3_ROBOT_DRIVER_ID, DEVICE_PROTOCOL_MODBUS_TCP, "Robot" },
	{ COFFEE3_DEVICE_COFFEE_MACHINE, 2U, 1U, 0U,
		DEVICE_CATEGORY_COFFEE_MACHINE,
		DEVICE_ROLE_COFFEE_MACHINE,
		DEVICE_DRIVER_COFFEE_M50_MODBUS,
		DEVICE_PROTOCOL_MODBUS_RTU, "M50" },
	{ COFFEE3_DEVICE_CUP_MACHINE, 3U, 1U, 0U,
		DEVICE_CATEGORY_CUP_MACHINE,
		DEVICE_ROLE_CUP_MACHINE, DEVICE_DRIVER_CUP_SHENGSHU_MODBUS,
		DEVICE_PROTOCOL_MODBUS_RTU, "Cup" },
	{ COFFEE3_DEVICE_SYRUP_MACHINE, 3U, 2U, 0U,
		DEVICE_CATEGORY_SYRUP_MACHINE,
		DEVICE_ROLE_SYRUP_MACHINE, DEVICE_DRIVER_SYRUP_CURRENT_MODBUS,
		DEVICE_PROTOCOL_MODBUS_RTU, "Syrup" },
	{ COFFEE3_DEVICE_LID_MACHINE, 3U, 1U, 0U,
		DEVICE_CATEGORY_LID_MACHINE,
		DEVICE_ROLE_LID_MACHINE, DEVICE_DRIVER_LID_SHENGSHU_MODBUS,
		DEVICE_PROTOCOL_MODBUS_RTU, "Lid" },
	{ COFFEE3_DEVICE_ICE_MACHINE, 4U, 1U,
		COFFEE3_ICE_MIN_FRAME_INTERVAL_MS,
		DEVICE_CATEGORY_ICE_MACHINE, DEVICE_ROLE_ICE_MACHINE,
		DEVICE_DRIVER_ICE_CURRENT_MODBUS, DEVICE_PROTOCOL_MODBUS_RTU, "Ice" },
	{ COFFEE3_DEVICE_SCALE, 4U, 2U, 0U,
		DEVICE_CATEGORY_SCALE, DEVICE_ROLE_SCALE,
		DEVICE_DRIVER_SCALE_BSQ_DG_V2, DEVICE_PROTOCOL_MODBUS_RTU, "Scale" },
	{ COFFEE3_DEVICE_POWER_METER, 3U, 3U, 0U,
		DEVICE_CATEGORY_POWER_METER,
		DEVICE_ROLE_POWER_METER, DEVICE_DRIVER_POWER_METER_DDSU666,
		DEVICE_PROTOCOL_MODBUS_RTU, "EnergyMeter" },
	{ COFFEE3_DEVICE_IO_INPUT, 5U, 1U,
		COFFEE3_IO_MIN_FRAME_INTERVAL_MS,
		DEVICE_CATEGORY_IO, DEVICE_ROLE_IO_INPUT,
		DEVICE_DRIVER_IO_MODBUS_DIGITAL, DEVICE_PROTOCOL_MODBUS_RTU, "IoInput16" },
	{ COFFEE3_DEVICE_IO_OUTPUT, 5U, 2U,
		COFFEE3_IO_MIN_FRAME_INTERVAL_MS,
		DEVICE_CATEGORY_IO, DEVICE_ROLE_IO_OUTPUT,
		DEVICE_DRIVER_IO_MODBUS_DIGITAL, DEVICE_PROTOCOL_MODBUS_RTU, "IoOutput16" }
};

#endif /* COFFEE3_DEVICE_BINDINGS_H */
